name: jdec
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.13
  - pip=21.2.2
  - numpy=1.19.2
  - pandas=1.1.5
  - cudatoolkit=11.3.1
  - pytorch=1.10.2
  - torchvision=0.11.3
  - pip:
      - dct-manip==0.2.3
      - einops==0.4.1
      - jpegio==0.2.8
      - matplotlib==3.3.4
      - opencv-python==4.5.5.64
      - pillow==8.4.0
      - psutil==5.9.4
      - pyyaml==6.0
      - scipy==1.5.4
      - tensorboard==2.10.1
      - tensorboardx==2.5
      - timm==0.5.4
      - tqdm==4.63.0
      - yacs==0.1.8
